version: "3.8"

services:
  glue-utils:
    image: glue-utils:latest
    build: .
    volumes:
      - .:/home/glue_user/workspace
    tty: true
    environment:
      - AWS_REGION=ap-southeast-2
      - DISABLE_SSL=true
