version: "3.8"

services:
  glue-utils:
    image: glue-utils:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - USER_ID=${USER_ID:-}
    volumes:
      - ..:/home/glue_user/workspace
    tty: true
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DISABLE_SSL=true
